# Generated by Django 2.0.3 on 2018-03-18 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brew',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
