# Generated by Django 2.0.3 on 2018-03-20 04:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0003_auto_20180320_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='regions',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
