# Generated by Django 2.0.3 on 2018-03-20 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0005_auto_20180320_0427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brew',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='coffee',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='roaster',
            name='is_removed',
        ),
    ]
